import os
from dotenv import load_dotenv

load_dotenv()

STRAVA_CLIENT_ID = os.getenv("STRAVA_CLIENT_ID")
STRAVA_CLIENT_SECRET = os.getenv("STRAVA_CLIENT_SECRET")
STRAVA_ACCESS_TOKEN = os.getenv("STRAVA_ACCESS_TOKEN")
STRAVA_REFRESH_TOKEN = os.getenv("STRAVA_REFRESH_TOKEN")
STRAVA_REDIRECT_URI = os.getenv("STRAVA_REDIRECT_URI")
MY_REFRESH_TOKEN = os.getenv("MY_REFRESH_TOKEN")
MONGO_URI = os.getenv("MONGO_URI")
REFRESH_TOKEN_SECRET_KEY= os.getenv("REFRESH_TOKEN_SECRET_KEY")